name: Test on push

on:
  push:
    branches:
      - main

env:
  GHCR_REGISTRY: yml.env.ghcr.io

jobs:
  prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Secret
        run: echo 'SOME_SECRET=${{ secrets.SOME_SECRET }}'
      - name: Env GHCR_REGISTRY
        run: echo 'env.GHCR_REGISTRY=${{ env.GHCR_REGISTRY }}'
      - name: Vars
        run: echo 'vars.GHCR_REGISTRY=${{ vars.GHCR_REGISTRY }}'
      - name: Secrets
        run: echo 'secrets.GH_TOKEN=${{ secrets.GH_TOKEN }}'
      - name: Invalid Secrets
        run: echo 'secrets.INVALID_TOKEN=${{ secrets.INVALID_TOKEN }}'
  sandbox:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Env GHCR_REGISTRY
        run: echo 'env.GHCR_REGISTRY=${{ env.GHCR_REGISTRY }}'
      - name: Vars
        run: echo 'vars.GHCR_REGISTRY=${{ vars.GHCR_REGISTRY }}'
      - name: Secrets
        run: echo 'secrets.INVALID_TOKEN=${{ secrets.INVALID_TOKEN }}'
