name: Test on push

on:
  push:
    branches:
      - main

env:
  GHCR_REGISTRY: yml.env.ghcr.io

jobs:
  prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Env GHCR_REGISTRY
        run: echo 'env.GHCR_REGISTRY=${{ env.GHCR_REGISTRY }}'
      - name: Vars
        run: echo 'vars.GHCR_REGISTRY=${{ vars.GHCR_REGISTRY }}'
  sandbox:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Env GHCR_REGISTRY
        run: echo 'env.GHCR_REGISTRY=${{ env.GHCR_REGISTRY }}'
      - name: Vars
        run: echo 'vars.GHCR_REGISTRY=${{ vars.GHCR_REGISTRY }}'
